export ACSetupSvcPort=23210
export ALLUSERSPROFILE=C:\ProgramData
export APPDATA=C:\Users\Ahzam Ali\AppData\Roaming
export CommonProgramFiles=C:\Program Files\Common Files
export CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
export CommonProgramW6432=C:\Program Files\Common Files
export COMPUTERNAME=HAYSTACK
export ComSpec=C:\WINDOWS\system32\cmd.exe
export DokanLibrary1=C:\Program Files\Dokan\Dokan Library-1.5.1\
export DokanLibrary1_LibraryPath_x64=C:\Program Files\Dokan\Dokan Library-1.5.1\lib\
export DokanLibrary1_LibraryPath_x86=C:\Program Files\Dokan\Dokan Library-1.5.1\x86\lib\
export DriverData=C:\Windows\System32\Drivers\DriverData
export EFC_13232_1592913036=1
export HOMEDRIVE=C:
export HOMEPATH=\Users\Ahzam Ali
export JAVA_HOME=D:\My Programs\jdk-25.0.1
export LOCALAPPDATA=C:\Users\Ahzam Ali\AppData\Local
export LOGONSERVER=\\HAYSTACK
export MOZ_PLUGIN_PATH=C:\Program Files (x86)\Nuance\PDF Professional 7\Bin\
export NUMBER_OF_PROCESSORS=16
export OneDrive=C:\Users\Ahzam Ali\OneDrive
export OneDriveConsumer=C:\Users\Ahzam Ali\OneDrive
export OS=Windows_NT
export Path=C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_2.6.2.0_x64__8wekyb3d8bbwe;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\PowerToys\DSCModules\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\Ahzam Ali\AppData\Local\Microsoft\WindowsApps;C:\Users\Ahzam Ali\AppData\Local\Programs\Microsoft VS Code\bin;D:\My Programs\Git\bin;C:\Program Files (x86)\Nmap;C:\Users\Ahzam Ali\AppData\Local\Programs\Antigravity\bin;D:\My Programs\maven-mvnd-1.0.3-windows-amd64\bin;D:\My Programs\maven-mvnd-1.0.3-windows-amd64\mvn\bin;D:\My Programs\gradle-9.2.1\bin;D:\My Programs\node-v24.12.0-win-x64;
export PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
export PROCESSOR_ARCHITECTURE=AMD64
export PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
export PROCESSOR_LEVEL=25
export PROCESSOR_REVISION=5000
export ProgramData=C:\ProgramData
export ProgramFiles=C:\Program Files
export ProgramFiles(x86)=C:\Program Files (x86)
export ProgramW6432=C:\Program Files
export PSModulePath=D:\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
export PUBLIC=C:\Users\Public
export RlsSvcPort=22112
export SESSIONNAME=Console
export SystemDrive=C:
export SystemRoot=C:\WINDOWS
export TEMP=C:\Users\AHZAMA~1\AppData\Local\Temp
export TMP=C:\Users\AHZAMA~1\AppData\Local\Temp
export USERDOMAIN=HAYSTACK
export USERDOMAIN_ROAMINGPROFILE=HAYSTACK
export USERNAME=Ahzam Ali
export USERPROFILE=C:\Users\Ahzam Ali
export windir=C:\WINDOWS
